### ISSUE TITLE
proper memory graphs

### ISSUE THREAD

**Issue by mihasya** [simplegeo/metartg#60]
we should graph things like buffers and caches so that it is easier to see true memory usage/pressure

sample:

<img src="http://monitor.millennium.berkeley.edu/graph.php?me=UC%20Berkeley&m=&r=hour&s=descending&hc=4&g=mem_report&z=medium&r=hour" />

**Comment by aguynamedben** [comment]
+1, real memory usage is pretty critical for debugging

**Comment by JeremyGrosser** [comment]
Done.
